name: Build and Push Docker Image

on:
    push:
        branches: [ main ]
    release:
        types: [ created ]

jobs:
    build_docker:
        name: Build docker
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Login to DockerHub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKER_HUB_USERNAME }}
                    password: ${{ secrets.DOCKER_HUB_SECRET }}

            -   name: Build Docker image
                run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/lictor:latest .

            -   name: Push Docker image
                run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/lictor:latest