name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [ 16.x, 18.x ]

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Set up Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node-version }}
            -   name: Install
                run: yarn install

            -   name: Run linter
                run: cd packages/server && yarn run lint

            -   name: Run linter
                run: cd packages/app && yarn run lint

            -   name: Build server
                run: cd packages/server && yarn run build
            -   name: Build app
                run: cd packages/app && yarn run build
